/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package ifepson.ifepson.doc;

import ifepson.ifepson.commands.*;

/**
 *
 * @author Administrador
 */
public enum Parametro {

    SE__TIPO_SOLICITUD          (   1, solEstado.class, DataType.Alfa,      1, "Tipo de informaciÃ³n solicitada. â€˜Nâ€™ InformaciÃ³n Normal o compatible con modelos anteriores. â€˜Pâ€™ InformaciÃ³n sobre las CaracterÃ­sticas del Controlador Fiscal. â€˜Câ€™ InformaciÃ³n sobre el contribuyente. â€˜Aâ€™ InformaciÃ³n sobre los contadores de documentos fiscales y no fiscales.â€˜Dâ€™ InformaciÃ³n sobre el documento que se esta emitiendo. â€˜Sâ€™ devuelve las preferencias del sistema", 0),
    XZ__TIPO_CIERRE             ( 100, cierreXZ.class, DataType.Alfa,      1, "Si se envÃ­a â€˜Zâ€™ 0x5a, ASCII (90 Decimal):Grabar Totales Diarios en la Memoria Fiscal y borrar los Totales Diarios de la Memoria de Trabajo. Se hace un Cierre â€˜Zâ€™. Si se envÃ­a â€˜Xâ€™ 0x58, ASCII (88 Decimal): Realizar un cambio de Cajero. Se hace un Cierre â€˜Xâ€™.", 0),
    XZ__IMPRIMIR                ( 101, cierreXZ.class, DataType.Alfa,      1, "Si se envÃ­a 'P' Ã³ 0x50 Ã³ ASCII (80 Decimal) el Reporte â€˜Xâ€™ sale impreso.", true, 1),
    RF__FECHA_INICIO            ( 201, repoMemFiscFecha.class, DataType.Fecha,     6, "Fecha de inicio de selecciÃ³n AAMMDD", 0),
    RF__FECHA_FIN               ( 202, repoMemFiscFecha.class, DataType.Fecha,     6, "Fecha de fin de selecciÃ³n AAMMDD", 1),
    RF__TIPO_REPORTE           ( 203, repoMemFiscFecha.class, DataType.Alfa,      1, "Se envÃ­a Â´TÂ´ 0x54 para un Total General, sin detalle diario como Documento No Fiscal con centavos (â€œReporte de Contadorâ€� resumido). Se envÃ­a Â´DÂ´ 0x44 para un reporte detallado como Documento No Fiscal con centavos (â€œReporte de Contadorâ€� con detalles). Se envÃ­a Â´tÂ´ 0x74 para un Total General, sin detalle diario como Documento Fiscal con redondeo al peso (â€œInforme de AuditorÃ­aâ€� resumido). Se envÃ­a Â´dÂ´ 0x64 para un reporte detallado como Documento Fiscal con redondeo al peso (â€œInforme de AuditorÃ­aâ€� con detalles).", 2),
    RZ__Z_INICIO                 ( 301, repoMemFiscZ.class, DataType.Integer,   4, "NÃºmero de Cierre Â´ZÂ´ inicial del rango elegido.", 0),
    RZ__Z_FIN                    ( 302, repoMemFiscZ.class, DataType.Integer,   4, "NÃºmero de Cierre Â´ZÂ´ final del rango elegido.", 1),
    RZ__TIPO_REPORTE           ( 303, repoMemFiscZ.class, DataType.Alfa,      1, "Se envÃ­a Â´TÂ´ 0x54 para un Total General, sin detalle diario como Documento No iscal con centavos (â€œReporte de Contadorâ€� resumido). Se envÃ­a Â´DÂ´ 0x44 para un reporte detallado como Documento No iscal con centavos (â€œReporte de Contadorâ€� con detalles). Se envÃ­a Â´tÂ´ 0x74 para un Total General, sin detalle diario como Documento iscal con redondeo al peso (â€œInforme de AuditorÃ­aâ€� resumido). Se envÃ­a Â´dÂ´ 0x64 para un reporte detallado como Documento iscal con redondeo al peso (â€œInforme de AuditorÃ­aâ€� con detalles).", 2),
    ABT__FORMATO_DATOS        (401, abrirTique.class, DataType.Alfa,            1, "Formato para almacenar los datos <a> â€˜Câ€™ ASCII(67) 0x43 Luego del Tique, no se va a realizar un Documento No Fiscal Homologado para Farmacias. â€˜Gâ€™ ASCII(71) 0x47 Se prepara el equipo para la impresiÃ³n del D.N.F.H. para Farmacias, cuando se termina de emitir el Tique.", true, 0),
    ITFT__DESCRIP_EXTRA         (501, imprTxtFiscTique.class, DataType.Alfa,           26, "LÃ­nea de DescripciÃ³n Extra en Tique: Texto Fiscal a Imprimir como lÃ­nea de descripciÃ³n extra previa a un Ã­tem de lÃ­nea en un Tique Fiscal. (MÃ¡ximo 26 caracteres).", 0),
    IIT__DESCRIPCION_PROD       (600, imprItemTique.class, DataType.Alfa,           26, "DescripciÃ³n del Ã­tem a vender. MÃ¡ximo 26 caracteres de Texto Fiscal. En caso de emitirse con tasa de IVA no estÃ¡ndar, el mÃ¡ximo serÃ¡ de 18 caracteres. En caso de, ademÃ¡s, poseer impuestos internos, el mÃ¡ximo que se imprimirÃ¡ serÃ¡ de 11 caracteres, truncando el resto.", 0),
    IIT__CANT_UNIDADES         (601, imprItemTique.class, DataType.Num3Dec,      8, "Cantidad de unidades. (nnnnn.nnn) Nota: Manejo de 5 enteros y 3 decimales, se debe enviar sin el punto.", 1),
    IIT__PRECIO_UNITARIO        (602, imprItemTique.class, DataType.Num4Dec,      12, "Precio Unitario del Item. (nnnnnnn.nnnn) Nota 1: Manejo de 7 enteros y 4 decimales, se debe enviar con el punto decimal. Nota 2: Compatible con manejo de 2 decimales (nnnnnnn.nn), en este caso se debe enviar 7 enteros y 2 decimales sin el punto decimal.", 2),
    IIT__TASA_IMPOSITIVA         (603, imprItemTique.class, DataType.Num2Dec,      4, "Tasa Impositiva. AlÃ­cuota de IVA (nn.nn) Nota: Se envÃ­a sin el punto decimal, por ejemplo 21,00 % de IVA se debe enviar â€œ2100â€�.", 3),
    IIT__CALIF_ITEM               (604, imprItemTique.class, DataType.Alfa,       1, "Calificador de Item de LÃ­nea: 'M'= 0x4d, Monto agregado de mercaderÃ­a o Ã­tem de venta, SUMA. 'm'= 0x6d, anula el Ã­tem vendido, RESTA. 'R'= 0x52, BonificaciÃ³n, RESTA. 'r'= 0x72, anula una BonificaciÃ³n, SUMA En el caso de BonificaciÃ³n, se antepone automÃ¡ticamente la leyenda â€œBONIF.â€� a la descripciÃ³n del artÃ­culo. ", 4),
    IIT__CANTIDAD_BULTOS       (605, imprItemTique.class, DataType.Integer,   5, "Unidades o Bultos Vendidos. (nnnnn.)", 5),
    IIT__TASA_AJUSTE_VAR        (606, imprItemTique.class, DataType.Num8Dec,     8, "Tasa de Ajuste Variable. (.nnnnnnnn) Nota: Se debe enviar sÃ³lo los decimales, hasta 8 dÃ­gitos, sin el punto. Ver documentaciÃ³n de modelos anteriores por detalles del cÃ¡lculo.", 6),
    IIT__IMPUESTO_INTERNO      (607, imprItemTique.class, DataType.Num8Dec,     15, "Monto Impuestos Internos Fijos. <nnnnnnn.nnnnnnnn>", 7),
    STT__IMPRIMIR               (608, subtotalTique.class, DataType.Alfa,       1, "ImpresiÃ³n del Subtotal: Si se envÃ­a â€˜Pâ€™ (0x50) se imprimirÃ¡ el Subtotal. Si se envÃ­a â€˜Nâ€™ (0x4E) no se imprimirÃ¡ el Subtotal (sÃ³lo se retornarÃ¡ la            informaciÃ³n a la PC en este caso).", 0),
    STT__DESCRIPCION           (609, subtotalTique.class, DataType.Alfa,       25, "NO SE UTILIZA", 1),
    PDRC__DESCRIPCION         (700, pagoCancelDescRecaTique.class, DataType.Alfa,      26, "DescripciÃ³n: Texto Fiscal Variable. MÃ¡ximo de 26 caracteres.", 0),
    PDRC__MONTO               (701, pagoCancelDescRecaTique.class, DataType.Num2Dec,      9, "Monto de Pago / Descuento / Recargo (nnnnnnnnn.nn) Nota: Manejo de 9 enteros y 2 decimales, se debe enviar sin el punto", 1),
    PDRC__CALIFICADOR         (702, pagoCancelDescRecaTique.class, DataType.Alfa,        1, "Calificador de Pago / Descuento / Recargo / Cancelar:  'C'= 0x43, Cancelar Comprobante.  'T'= 0x54, Suma al Importe Pagado.  't'= 0x74, Anula un Pago hecho con â€˜Tâ€™.  'D'= 0x44, Realiza un descuento global por monto fijo.  'R'= 0x44, Realiza un recargo global por monto fijo.", 2),
    CT__CORTE_TOTAL           (800, cerrarTique.class, DataType.Alfa,       1, "Tipo de Corte sobre el papel al finalizar la impresiÃ³n â€˜Tâ€™ Corte Total (Recomendado). â€˜Pâ€™ Corte Parcial. Nota: Si no fuera soportada esta opciÃ³n el IF efectuarÃ¡ un Corte Total", 0),
    ITDNF__DESCRIPCION        (900, imprTxtDNF.class, DataType.Alfa,      40, "Hasta 40 Caracteres de Texto No Fiscal", 0),
    CDNF__CORTE_TOTAL        (1000, cerrarDNF.class, DataType.Alfa,       1, "Tipo de Corte sobre el papel al finalizar la impresiÃ³n â€˜Tâ€™ Corte Total (Recomendado). â€˜Pâ€™ Corte Parcial. Nota: Si no fuera soportada esta opciÃ³n el IF efectuarÃ¡ un Corte Total", 0),
    CNFHTC__01                 (1100, DNFHTarjetaCredito.class, DataType.Integer,    2, "â€˜01â€™ Comprobante No Fiscal Homologado Voucher Tarjeta de CrÃ©dito <0x30,0x31> <nn>.", 0),
    CNFHTC__NOMBRE_TARJETA  (1101, DNFHTarjetaCredito.class, DataType.Alfa,      34, "DescripciÃ³n de Texto Fiscal Variable para identificar el nombre de la tarjeta de crÃ©dito. Longitud mÃ¡xima 34 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 1),
    CNFHTC__NRO_TARJETA      (1102, DNFHTarjetaCredito.class, DataType.Alfa,      31, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de la tarjeta de crÃ©dito. Longitud mÃ¡xima 31 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 2),
    CNFHTC__USUARIO           (1103, DNFHTarjetaCredito.class, DataType.Alfa,      31, "DescripciÃ³n de Texto Fiscal Variable para identificar el nombre del usuario de la tarjeta de crÃ©dito. Longitud mÃ¡xima 31 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 3),
    CNFHTC__VENC_TARJ         (1104, DNFHTarjetaCredito.class, DataType.Fecha,      6, "Fecha de vencimiento de la tarjeta de crÃ©dito. El formato es AAMMDD (AÃ±o, mes, dÃ­a). Dado que las tarjetas de crÃ©dito no tienen el dÃ­a de vencimiento, se debe enviar el dÃ­a 01. Si se envÃ­a â€˜000000â€™no se imprime esta lÃ­nea. <AAMMDD>", 4),
    CNFHTC__NRO_ESTAB        (1105, DNFHTarjetaCredito.class, DataType.Alfa,       26, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de establecimiento. Longitud mÃ¡xima 26 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 5),
    CNFHTC__NRO_CUPON       (1106, DNFHTarjetaCredito.class, DataType.Alfa,      28, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de cupÃ³n. Longitud mÃ¡xima 28 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 6),
    CNFHTC__NRO_INT_COMP    (1107, DNFHTarjetaCredito.class, DataType.Alfa,      25, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero interno del comprobante que se esta emitiendo. Es un nÃºmero de referencia interna que se utiliza en algunos supermercados. Longitud mÃ¡xima 25 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 7),
    CNFHTC__COD_AUTORIZ     (1108, DNFHTarjetaCredito.class, DataType.Alfa,      25, "DescripciÃ³n de Texto Fiscal Variable para identificar el cÃ³digo autorizaciÃ³n de la transacciÃ³n electrÃ³nica. Longitud mÃ¡xima 25 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 8),
    CNFHTC__TIPO_OPERAC      (1109, DNFHTarjetaCredito.class, DataType.Alfa,      29, "DescripciÃ³n de Texto Fiscal Variable para identificar el tipo de operaciÃ³n. Longitud mÃ¡xima 29 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 9),
    CNFHTC__IMPORTE          (1110, DNFHTarjetaCredito.class, DataType.Num4Dec,  11, "Importe que se debe pagar. Formato <nnnnnnnnn.nn> (se debe enviar sin punto decimal). En caso de enviar un dato errÃ³neo o no enviar un dato se imprimirÃ¡ importe nulo.", 10),
    CNFHTC__CANT_CUOTAS     (1111, DNFHTarjetaCredito.class, DataType.Alfa,       26, "DescripciÃ³n de Texto Fiscal Variable para identificar la cantidad de cuotas.Longitud mÃ¡xima 26 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 11),
    CNFHTC__MONEDA          (1112, DNFHTarjetaCredito.class, DataType.Alfa,       32, "DescripciÃ³n de Texto Fiscal Variable para identificar el tipo de moneda en que se ha realizado la transacciÃ³n. Longitud mÃ¡xima 32 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 12),
    CNFHTC__NRO_TERMINAL    (1113, DNFHTarjetaCredito.class, DataType.Alfa,       25, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de terminal. Es un nÃºmero interno que se usa en algunos supermercados. Longitud mÃ¡xima 25 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 13),
    CNFHTC__NRO_LOTE         (1114, DNFHTarjetaCredito.class, DataType.Alfa,       29, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de lote. Es un nÃºmero interno que se usa en algunos supermercados. Longitud mÃ¡xima 29 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 14),
    CNFHTC__NRO_TERM_ELEC   (1115, DNFHTarjetaCredito.class, DataType.Alfa,       27, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de terminal electrÃ³nica. Es un nÃºmero interno que se usa uso en algunos supermercados. Longitud mÃ¡xima 27 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 15),
    CNFHTC__NRO_SUCURSAL    (1116, DNFHTarjetaCredito.class, DataType.Alfa,       25, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de sucursal. Longitud mÃ¡xima 25 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 16),
    CNFHTC__OPERADOR        (1117, DNFHTarjetaCredito.class, DataType.Alfa,       30, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero o nombre del operador. Longitud mÃ¡xima 30 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 17),
    CNFHTC__NRO_FACTURA     (1118, DNFHTarjetaCredito.class, DataType.Alfa,      29, "DescripciÃ³n de Texto Fiscal Variable para identificar el nÃºmero de Documento Fiscal al que se hace referencia. Longitud mÃ¡xima 29 Caracteres. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 18),
    CNFHTC__LINEA_FIRMA      (1119, DNFHTarjetaCredito.class, DataType.Alfa,       1, "Si se envÃ­a el Caracter letra â€˜Pâ€™ (0x50) (80 Decimal) se deja un espacio para que el cliente firme <a>. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 19),
    CNFHTC__LINEA_ACLARA     (1120, DNFHTarjetaCredito.class, DataType.Alfa,       1, "Si se envÃ­a el Caracter letra â€˜Pâ€™ (0x50) (80 Decimal) se deja un espacio para que el cliente ponga un nÃºmero de telÃ©fono. Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime esta lÃ­nea.", 20),
    CNFHTC__LINEA_TELEFONO   (1121, DNFHTarjetaCredito.class, DataType.Alfa,       1, "Si se envÃ­a el Caracter letra â€˜Pâ€™ (0x50) (80 Decimal) se deja un espacio para que el cliente ponga su nÃºmero de Documento <a>.Si se envÃ­a el Caracter DEL (0x7F) Ã³ (127 en decimal) no se imprime", 21),
    SPU__IMPRESORA            (1300, selPrefUsuario.class, DataType.Alfa,       1, "Se debe enviar â€˜Pâ€™ 0x50 - ASCII (80 Decimal) para indicar que se establecerÃ¡n las preferencias de la impresora.", 0),
    SPU__TIPO_SETEO            (1301, selPrefUsuario.class, DataType.Alfa,       1, "Posibles valores: â€˜Dâ€™ 0x44 ASCII (68 Decimal) se envÃ­a para indicar que se setearÃ¡n las preferencias del dispositivo a utilizar para la impresiÃ³n. â€˜Pâ€™ 0x50 ASCII (80 Decimal) se envÃ­a para indicar que se establecerÃ¡n las preferencias del papel a utilizar. â€˜Tâ€™ 0x54 ASCII (84 Decimal) se envÃ­a para indicar que se establecerÃ¡n las preferencias de los comprobantes fiscales.", 1),
    SPU__OPCIONES1            (1302, selPrefUsuario.class, DataType.Alfa,       1, "Si en el Campo 02 se envÃ­o â€˜Dâ€™: â€˜Sâ€™ 0x53 ASCII (83 Decimal)para indicar que se utilizarÃ¡ como estaciÃ³n seleccionada por el usuario el slip paper (hoja suelta). â€˜Râ€™ 0x52 ASCII (82 Decimal)para indicar que se utilizarÃ¡ como estaciÃ³n seleccionada por el usuario la de rollo de papel. Si en el Campo 02 se envÃ­o â€˜Pâ€™: â€˜Sâ€™ 0x53 ASCII(83 Decimal)indica que se establecerÃ¡ el tamaÃ±o de papel. Si en el Campo 02 se envÃ­o â€˜Tâ€™: â€˜Pâ€™ 0x50 ASCII (80 Decimal) se envÃ­a para indicar que se establecerÃ¡n las preferencias de imprimir las leyendas â€œSuma de sus pagosâ€� y â€œSu Vueltoâ€�. â€˜Qâ€™ 0x51 ASCII (81 Decimal) se envÃ­a para indicar que se establecerÃ¡n las preferencias de imprimir Precio por Cantidad en cada Ã­tem facturado.", 2),
    SPU__OPCIONES2            (1303, selPrefUsuario.class, DataType.Alfa,       1, "Si en el Campo 02 se enviÃ³ â€˜Dâ€™: â€˜Oâ€™ 0x4F ASCII (79 Decimal) establece que se imprimirÃ¡n los Documentos No Fiscales por la estaciÃ³n seleccionada en el Campo 03. Si en el Campo 03 se enviÃ³ â€˜Sâ€™: â€˜Uâ€™ 0x55 ASCII (85 Decimal) establece que se utilizarÃ¡ un tamaÃ±o definido por el usuario. Si en el campo 03 se enviÃ³ â€˜Pâ€™ o â€˜Qâ€™: â€˜Nâ€™ 0x4E ASCII(78 Decimal) deselecciona la preferencia respectiva. â€˜Sâ€™ 0x53 ASCII(83 Decimal) selecciona la preferencia respectiva. ", 3),
    SPU__CANT_COLUMNAS      (1304, selPrefUsuario.class, DataType.Integer,     1, "SÃ³lo si en el Campo 04 se enviÃ³ â€˜Uâ€™: Establece la cantidad de lÃ­neas que mide el papel (slip) a utilizar. Para el EPSON TM-950F se consideran 6 lÃ­neas por cada 2,54 cm. (mÃ­nimo 10. mÃ¡ximo 999). Para el EPSON TM-U675F este seteo es ignorado y sÃ³lo acepta un valor de 2 dÃ­gitos, es decir hasta 99). Nota 1: Se debe enviar el largo del papel en lÃ­neas. El Impresor Fiscal descuenta las lÃ­neas que no pueden ser impresas por las CaracterÃ­sticas de la impresora utilizada. Nota 2: En el caso de las impresoras tipo TM-U950, se descuentan cuatro lÃ­neas. Nota 3: Si el usuario ingresa un papel de menor tamaÃ±o al enviado en este campo, la impresiÃ³n del documento puede ser abortada. ", 4),
    SPU__CANT_FILAS            (1305, selPrefUsuario.class, DataType.Integer,    1, "SÃ³lo si en el Campo 04 se enviÃ³ â€˜Uâ€™: Establece la cantidad de lÃ­neas que mide el papel (slip) a utilizar. Para el EPSON TM-950F se consideran 6 lÃ­neas por cada 2,54 cm. mÃ­nimo 10. mÃ¡ximo 999). Para el EPSON TM-U675F este seteo es ignorado y sÃ³lo acepta un valor de 2 dÃ­gitos, es decir hasta 99). Nota 1: Se debe enviar el largo del papel en lÃ­neas. El Impresor Fiscal descuenta las lÃ­neas que no pueden ser impresas por las CaracterÃ­sticas de la impresora utilizada. Nota 2: En el caso de las impresoras tipo TM-U950, se descuentan cuatro lÃ­neas. Nota 3: Si el usuario ingresa un papel de menor tamaÃ±o al enviado en este campo, la impresiÃ³n del documento puede ser abortada. ", 5),
    LPU__IMPRESORA            (1400, leePrefUsuario.class, DataType.Alfa,       1, "Se debe enviar â€˜Pâ€™ 0x50 - ASCII (80 Decimal) para indicar que se leerÃ¡n las preferencias de la impresora.", 0),
    LPU__TIPO_SETEO            (1401, leePrefUsuario.class, DataType.Alfa,       1, "Posibles valores: â€˜Dâ€™ 0x44 ASCII (68 Decimal) para indicar que se leerÃ¡n las preferencias del dispositivo a utilizar para la impresiÃ³n. â€˜Pâ€™ 0x50 ASCII (80 Decimal) para indicar que se leerÃ¡n las preferencias del papel a utilizar para la impresiÃ³n. â€˜Tâ€™ 0x54 ASCII (84 Decimal) para indicar que se leerÃ¡n las preferencias de los comprobantes fiscales.", 1),
    LPU__OPCIONES1            (1402, leePrefUsuario.class, DataType.Alfa,       1, "Si en el Campo 02 se enviÃ³ â€˜Pâ€™: Enviar â€˜Sâ€™ 0x53 ASCII (83 Decimal) para indicar que se leerÃ¡n las preferencias del tamaÃ±o del papel a utilizar en la impresiÃ³n. Si en el Campo 02 se enviÃ³ â€˜Tâ€™: Enviar â€˜Pâ€™ 0x50 ASCII (80 Decimal) para indicar que se leerÃ¡n las preferencias de imprimir las leyendas â€œSuma de sus pagosâ€� y â€œSu Vueltoâ€�. Enviar â€˜Qâ€™ 0x51 ASCII (81 Decimal) para indicar que se leerÃ¡n las preferencias de imprimir Precio por Cantidad en cada Ã­tem facturado.", 2),
    PEP__MANEJO_DOCUMENTO  (1500, prepararEstacion.class, DataType.Alfa,       1, "Se debe enviar â€˜Dâ€™ 0x44 - ASCII (68 Decimal) para indicar que se enviarÃ¡ un comando de manejo de documentos. ", 0),
    PEP__IMPRESION            (1501, prepararEstacion.class, DataType.Alfa,       1, "Se debe enviar â€˜Pâ€™ 0x50 - ASCII (80 Decimal) para indicar que se enviarÃ¡ un comando para la impresiÃ³n.", 1),
    PEP__IMPRESION1           (1502, prepararEstacion.class, DataType.Alfa,       1, "Se debe enviar â€˜Pâ€™ 0x50 - ASCII (80 Decimal) para indicar que deberÃ¡ preparar para la impresiÃ³n, la estaciÃ³n seleccionada en el Campo 04.", 2),
    PEP__IMP_DNF_HOJA_SUEL   (1503, prepararEstacion.class, DataType.Alfa,       1, "Uâ€™ 0x55 ASCII (85 Decimal) Prepara la estaciÃ³n definida en las preferencias del usuario. Para imprimir Documentos No Fiscales por hoja suelta, se debe utilizar esta opciÃ³n.", 3),
    PEP__IMP_DNF              (1504, prepararEstacion.class, DataType.Alfa,       1, "â€˜Oâ€™ 0x4F ASCII (79 Decimal) indica que deberÃ¡ preparar la estaciÃ³n seleccionada se acuerdo al Campo 04 para la impresiÃ³n de un Documento No Fiscal.", 4),
    AVT__TIPO_AVANCE          (1501, null, DataType.Hexa,                       1, "Comando 0x50 - ASCII '(80 Decimal), Comando 0x51 - ASCII (81 Decimal) Ã³ Comando 0x52 - ASCII (82 Decimal).", 0),
    AVT__CANTIDAD_LINEAS      (1502, avanzaTique.class, DataType.Integer,       2, "Cantidad de lineas", 0),
    AHS__CANTIDAD_LINEAS      (1600, avanzaHojaSuelta.class, DataType.Integer,    2, "Cantidad de lineas", 0),
    EFH__FECHA                 (1700, setFechaHora.class, DataType.Fecha,       6, "Fecha AAMMDD", 0),
    EFH__HORA                  (1701, setFechaHora.class, DataType.Hora,       6, "Hora HHMMSS", 1),
    AFNC__TIPO_DOC_FISCAL     (1800, abrirFNC.class, DataType.Alfa,      1, "Tipo de Documento Fiscal que se va a realizar: <a> (SegÃºn modelo) â€˜Fâ€™= 0x46 Factura Fiscal â€˜Nâ€™= 0x4E Nota de CrÃ©dito Fiscal â€˜Tâ€™= 0x54 Tique-Factura Fiscal â€˜Mâ€™= 0x4D Tique-Nota de CrÃ©dito Fiscal", 0),
    AFNC__TIPO_SALIDA_IMPRESA (1801, abrirFNC.class, DataType.Alfa,     1,"Tipo de Salida Impresa <a> para Factura Fiscal o Recibo â€“ Factura â€˜Câ€™= Formulario Continuo. â€˜Sâ€™= Hoja Suelta Ã³ Impresora Slip. NOTA: Si el Campo 01 es â€˜Tâ€™ o â€˜Mâ€™ este valor es ignorado.", true, 1),
    AFNC__LETRA_DOCUMENTO   (1802, abrirFNC.class, DataType.Alfa,     1, "Letra del Documento Fiscal <a> â€˜Aâ€™= 0x41 Ã³ â€˜Bâ€™= 0x42 Ã³ â€˜Câ€™= 0x43 Ã³ â€˜Xâ€™=0x58 Cualquier otra letra origina que se rechace el comando.", true, 2),
    AFNC__CANT_COPIAS         (1803, abrirFNC.class, DataType.Integer,  1, "Cantidad de Copias que se deben IMPRIMIR.<n> Si usa copia con CarbÃ³nico, debe enviar â€˜1â€™, pero si desea utilizar solo hojas en original, debe enviar como mÃ­nimo â€˜2â€™. Este campo sÃ³lo es necesario para Facturas Fiscales en hoja suelta o formulario continuo. IMPORTANTE: En el caso de impresiÃ³n en rollo (T, TF, TNC) Ã©ste valor es ignorado.", true, 3),
    AFNC__TIPO_FORMULARIO    (1804, abrirFNC.class, DataType.Alfa,     1, "Tipo de Formulario que se utiliza para la Factura emitidas en hoja suelta o formulario continuo. <a> Indica si la impresora fiscal debe o no dibujar las lÃ­neas de las facturas emitidas en hoja suelta o formulario continuo. Este campo sÃ³lo es necesario para Facturas Fiscales. En el caso de Tique-Factura / Tique-Nota de CrÃ©dito, este dato es ignorado. Los valores posibles son: â€˜Fâ€™= 0x46 : Se utiliza formulario pre-impreso con las lÃ­neas de la factura dibujadas.â€˜Pâ€™= 0x50: La impresora fiscal debe dibujar las lÃ­neas de la factura Impreso por la Impresora. â€˜Aâ€™= 0x41: Autoimpresor, no imprimir todo el encabezado.", true, 4),
    AFNC__DENSIDAD_LETRA      (1805, abrirFNC.class, DataType.Integer,  2, "Densidad de ImpresiÃ³n de los caracteres que se va a utilizar. VÃ¡lido para Factura emitida en hoja suelta o formulario continuo. <nn> La Densidad o ResoluciÃ³n de ImpresiÃ³n no puede ser modificada en el transcurso de una Factura en hoja suelta o formulario continuo.Se han redondeado los CPI, por lo tanto para imprimir a 16,7 CPI, se debe enviar el nÃºmero 17 y no 16,7. Valores aceptados para facturas en hoja suelta o formulario continuo, segÃºn modelo: â€˜12â€™ CPI = 0x31 0x32 â€˜17â€™ CPI = 0x31 0x37 En Tique-Factura / Tique-Nota de CrÃ©dito este valor es ignorado y se imprime siempre a 16,7 CPI. En caso de enviar un valor no aceptado por el equipo, el mismo es ignorado y no reporta error.", true, 5),
    AFNC__RESP_AFIP_VENDEDOR (1806, abrirFNC.class, DataType.Alfa,     1, "Responsabilidad Frente al IVA del EMISOR en el modo entrenamiento En modo entrenamiento, este campo era obligatorio que tenga una opciÃ³n vÃ¡lida, en cambio en la nueva lÃ­nea de impresoras fiscales es obligatorio configurar los datos fiscales para poder emitir documentos fiscales en modo entrenamiento, por lo que se utilizarÃ¡ la categorÃ­a del emisor configurada junto con el resto de los datos fiscales. Los valores posibles son: â€˜Iâ€™= 0x49 IVA RESPONSABLE INSCRIPTO â€˜Râ€™= 0x52 IVA RESPONSABLE NO INSCRIPTO â€˜Nâ€™= 0x4E NO RESPONSABLE â€˜Eâ€™= 0x45 IVA EXENTO â€˜Mâ€™= 0x4D RESPONSABLE MONOTRIBUTO â€˜Tâ€™= 0x54 MONOTRIBUTISTA SOCIAL Cualquier letra distinta de I,R,N,E,M,T serÃ¡ rechazada.", true, 6),
    AFNC__RESP_AFIP_COMPRADOR(1807, abrirFNC.class, DataType.Alfa,    1, "Responsabilidad Frente al IVA del COMPRADOR. Este campo es obligatorio que tenga siempre una opciÃ³n vÃ¡lida. Los valores posibles son: â€˜Iâ€™= 0x49 IVA RESPONSABLE INSCRIPTO â€˜Râ€™= 0x52 IVA RESPONSABLE NO INSCRIPTO â€˜Nâ€™= 0x4E NO RESPONSABLE â€˜Eâ€™= 0x45 IVA EXENTO â€˜Mâ€™= 0x4D RESPONSABLE MONOTRIBUTO â€˜Fâ€™= 0x46 CONSUMIDOR FINAL â€˜Sâ€™= 0x53 SUJETO NO CATEGORIZADO â€˜Tâ€™= 0x54 MONOTRIBUTISTA SOCIAL â€˜Câ€™= 0x43 PEQUEÃ‘O CONTRIBUYENTE EVENTUAL â€˜Vâ€™= 0x56 PEQUEÃ‘O CONTRIBUYENTE EVENTUAL SOCIAL Cualquier letra distinta de I,R,N,E,M,F,S,T,C,V serÃ¡ rechazada. Si el sujeto es â€œNo Categorizadoâ€�, se deberÃ¡ realizar la percepciÃ³n que corresponde por RG212. Importante: Si se intenta generar un documento que no es posible por la RG-259, por ejemplo tratar de realizar una venta de responsable Inscripto a responsable Inscripto una factura tipo â€˜Câ€™, se informa error en este campo.", 7),
    AFNC__NOMBRE_COMPRAD_L1 (1808, abrirFNC.class, DataType.Alfa,    40, "Nombre Comercial Comprador Primer LÃ­nea de Texto Fiscal Variable Cantidad mÃ¡xima de caracteres segÃºn modelo (segÃºn densidad de impresiÃ³n seleccionada y configuraciÃ³n de las zonas de impresiÃ³n). El mÃ¡ximo cuando se emiten T/TF/TNC es de 40 caracteres impresos. Si por ejemplo se imprime en modo doble ancho, se reducirÃ¡ la cantidad de caracteres impresos a la mitad.", 8),
    AFNC__NOMBRE_COMPRAD_L2 (1809, abrirFNC.class, DataType.Alfa,    40, "Nombre Comercial Comprador Segunda LÃ­nea de Texto FiscalVariable â€“ Cantidad mÃ¡xima de caracteres segÃºn modelo. Ver campo anterior con mÃ¡s detalles.", true, 9),
    AFNC__TIPO_DOC_COMPRADOR(1810, abrirFNC.class, DataType.Alfa,     6, "Tipo de Documento del Comprador. <aaaaaa> Texto ASCII de hasta 6 Caracteres; si dice â€˜CUITâ€™ o â€˜CUILâ€™, se verifica el nÃºmero enviado. Se debe enviar un CUIT Ã³ CUIL siempre que el comprador no sea un Consumidor Final.", 10),
    AFNC__CUIT_COMPRADOR     (1811, abrirFNC.class, DataType.Integer, 11, "NÃºmero de C.U.I.T. o de Documento del Comprador. Nro.: XX-XXXXXXXX-X: <nnnnnnnnnnn> Se aceptan 11 nÃºmeros sin los guiones. SerÃ¡ validado en CUIT Ã³ CUIL (Si se emite un comprobante Tipo A). ", 11),
    AFNC__LEYENDA_BIEN_USO    (1812, abrirFNC.class, DataType.Boolean, 1, "Leyenda OPCIONAL Bien de USO â€˜Bâ€™= 0x42 -Se imprime la leyenda â€œVTA. BIENES DE USOâ€�. â€˜Nâ€™= 0x4E -No se imprime la leyenda anterior. Esta opciÃ³n sÃ³lo era vÃ¡lida si la responsabilidad del emisor era â€œResponsable Inscriptoâ€�, la del comprador era â€œResponsable No Inscriptoâ€� y se emitÃ­a un Documento Fiscal tipo Tique-Factura B Ã³ Factura B. NOTA: Dado que por RG1697 / ley 25865 se ha eliminado la categorÃ­a â€œResponsable No Inscriptoâ€�, este dato ya no es requerido por lo que serÃ¡ ignorado en caso de ser enviado. ", true, 12),
    AFNC__DOMIC_COMPRADOR_L1(1813, abrirFNC.class, DataType.Alfa,    40, "Domicilio Comprador, Primera LÃ­nea de Texto Fiscal Variable Cantidad mÃ¡xima de caracteres segÃºn modelo (segÃºn densidad de impresiÃ³n seleccionada y configuraciÃ³n de las zonas de impresiÃ³n). El mÃ¡ximo cuando se emiten T/TF/TNC es de 40 caracteres impresos. Si por ejemplo se imprime en modo doble ancho, se reducirÃ¡ la cantidad de caracteres impresos a la mitad.", 13),
    AFNC__DOMIC_COMPRADOR_L2(1814, abrirFNC.class, DataType.Alfa,    40, "Domicilio Comprador, Segunda LÃ­nea de Texto Fiscal Variable Cantidad mÃ¡xima de caracteres segÃºn modelo. Ver campo anterior", true, 14),
    AFNC__DOMIC_COMPRADOR_L3(1815, abrirFNC.class, DataType.Alfa,    40, "Domicilio Comprador, Tercera LÃ­nea de Texto Fiscal Variable Cantidad mÃ¡xima de caracteres segÃºn modelo. Ver campo anterior", true, 15),
    AFNC__REMITOS_RELAC_L1    (1816, abrirFNC.class, DataType.Alfa,    40, "Remitos Relacionados, Primer lÃ­nea - Texto Fiscal Variable con Datos sobre los remitos relacionados con la operaciÃ³n de venta. Cantidad mÃ¡xima de caracteres segÃºn modelo (segÃºn densidad de impresiÃ³n seleccionada y configuraciÃ³n de las zonas de impresiÃ³n). El mÃ¡ximo cuando se emiten T/TF/TNC es de 40 caracteres impresos. Si por ejemplo se imprime en modo doble ancho, se reducirÃ¡ la cantidad de caracteres impresos a la mitad. En Nota de CrÃ©dito y Tique-Nota de CrÃ©dito este campo se usa para indicar Tipo y NÃºmero de Comprobante de Venta de Origen. En este caso el mÃ¡ximo cuando se emite TNC es de 21 caracteres impresos.", 16),
    AFNC__REMITOS_RELAC_L2    (1817, abrirFNC.class, DataType.Alfa,    40, "Remitos Relacionados, Segunda LÃ­nea de Texto Fiscal Variable con datos sobre los remitos relacionados. Cantidad mÃ¡xima de caracteres segÃºn modelo. Ver campo anterior con mÃ¡s detalles.", true, 17),
    AFNC__FORMATO_ALMAC_DAT (1818, abrirFNC.class, DataType.Alfa,     1, "Formato para almacenar los datos â€˜Câ€™= 0x43 -Luego del Tique/Tique-Factura, no se va a realizar un Documento No Fiscal Homologado para Farmacias. IMPORTANTE: Normalmente se debe usar esta opciÃ³n â€˜Câ€™ , excepto cuando se emiten Tiques en FARMACIAS. â€˜Gâ€™= 0x47 -Se prepara el equipo para la impresiÃ³n del D.N.F.H. para Farmacias, cuando se termina de emitir el Tique/TF. IMPORTANTE: Usar la opciÃ³n â€˜Gâ€™, UNICAMENTE CUANDO ES NECESARIO EMITIR un D.N.F.H. para las Farmacias.", true, 18),
    IIFNC__DESCRIPCION_PROD   (1900, imprItemFNC.class, DataType.Alfa,    18, "DescripciÃ³n del producto o bien facturado. LÃ­nea de Texto Fiscal Variable â€“ Cantidad mÃ¡xima de caracteres segÃºn modelo. El mÃ¡ximo cuando se emite TF/TNC es de 18 caracteres impresos cuando no existen impuestos internos y 11 caracteres en los casos en que existen impuestos internos. En el caso de las facturas en hoja suelta, este valor depende de la resoluciÃ³n a la que se imprime (CPIs) y del tamaÃ±o del papel utilizado.", 0),
    IIFNC__CANT_UNIDADES      (1901, imprItemFNC.class, DataType.Num3Dec,     8, "Cantidad de unidades. (nnnnn.nnn) Nota: Manejo de 5 enteros y 3 decimales, se debe enviar sin el punto.", 1),
    IIFNC__PRECIO_UNITARIO     (1902, imprItemFNC.class, DataType.Num4Dec,    12, "Precio Unitario del Item. (nnnnnnn.nnnn) Para FACTURAS A, SE ESPERAN VALORES SIN IVA. Para FACTURAS B, SE ESPERAN VALORES CON IVA. Para FACTURAS C, SE ESPERAN VALORES CON IVA. Nota 1: Manejo de 7 enteros y 4 decimales, se debe enviar con el punto decimal. Nota 2: Compatible con manejo de 2 decimales (nnnnnnn.nn), en este caso se debe enviar 7 enteros y 2 decimales sin el punto decimal.", 2),
    IIFNC__TASA_IVA             (1903, imprItemFNC.class, DataType.Num2Dec,     4, "Tasa Impositiva. AlÃ­cuota de IVA (nn.nn) Nota: Se envÃ­a sin el punto decimal, por ejemplo 21,00 % de IVA se debe enviar â€œ2100â€�.", 3),
    IIFNC__CALIF_ITEM           (1904, imprItemFNC.class, DataType.Alfa,      1, "Calificador de Item de LÃ­nea: 'M'= 0x4d, Monto agregado de mercaderÃ­a o Ã­tem de venta, SUMA. 'm'= 0x6d, anula el Ã­tem vendido, RESTA. 'R'= 0x52, BonificaciÃ³n, RESTA. 'r'= 0x72, anula una BonificaciÃ³n, SUMA En el caso de BonificaciÃ³n, se antepone automÃ¡ticamente la leyenda â€œBONIF.â€� a la descripciÃ³n del artÃ­culo.", 4),
    IIFNC__CANTIDAD_BULTOS    (1905, imprItemFNC.class, DataType.Integer,   5, "Cantidad de bultos: (no se usa) (nnnnn.)", 5),
    IIFNC__TASA_AJUSTE_VAR     (1906, imprItemFNC.class, DataType.Num8Dec,     8, "Tasa de Ajuste Variable. (.nnnnnnnn) IMPORTANTE: La tasa de ajuste Variable para Documentos Fiscales tipo â€˜Aâ€™; se calcula en forma diferente que los Documentos Fiscales tipo â€˜Bâ€™, ver documentaciÃ³n de modelos anteriores por detalles. Nota: Se debe enviar sÃ³lo los decimales, hasta 8 dÃ­gitos, sin el punto.", 6),
    IIFNC__DESCRIP_EXTRA_1     (1907, imprItemFNC.class, DataType.Alfa,     26, "DescripciÃ³n Extra LÃ­nea NÃºmero 1. Texto Fiscal Variable - Cantidad mÃ¡xima de caracteres segÃºn modelo, 26 caracteres para TF/TNC.", true, 7),
    IIFNC__DESCRIP_EXTRA_2     (1908, imprItemFNC.class, DataType.Alfa,     26, "DescripciÃ³n Extra LÃ­nea NÃºmero 2. Texto Fiscal Variable - Cantidad mÃ¡xima de caracteres segÃºn modelo, 26 caracteres para TF/TNC.", true, 8),
    IIFNC__DESCRIP_EXTRA_3     (1909, imprItemFNC.class, DataType.Alfa,     26, "DescripciÃ³n Extra LÃ­nea NÃºmero 3. Texto Fiscal Variable - Cantidad mÃ¡xima de caracteres segÃºn modelo, 26 caracteres para TF/TNC.", true, 9),
    IIFNC__TASA_ACRECENTAM    (1910, imprItemFNC.class, DataType.Num2Dec,     4, "Tasa de Acrecentamiento. 10,50 % (cuando un Responsable Inscripto vende a un Responsable NO INSCRIPTO) (nnnn) . NOTA: Dado que por RG1697 / ley 25865 se ha eliminado la categorÃ­a â€œResponsable No Inscriptoâ€�, este dato ya no es requerido por lo que serÃ¡ ignorado en caso de ser enviado.", true, 10),
    IIFNC__MONTO_IMP_INT_FIJO  (1911, imprItemFNC.class, DataType.Num8Dec,     15, "Monto Impuestos Internos Fijos. <nnnnnnn.nnnnnnnn> Nota: Manejo de 7 enteros y 8 decimales, se debe enviar sin el punto. Se soporta 8 decimales por compatibilidad con modelos anteriores pero se realiza el cÃ¡lculo con el valor enviado (unitario) redondeado a 4 decimales y se imprime el resultado con dos decimales. ", true, 11),
    STFNC__IMPRIMIR            (2000, subtotalFNC.class, DataType.Boolean,   1, "ImpresiÃ³n del Subtotal: Si se envÃ­a â€˜Pâ€™ (0x50) se imprimirÃ¡ el Subtotal. Si se envÃ­a â€˜Nâ€™ (0x4E) no se imprimirÃ¡ el Subtotal (sÃ³lo se retornarÃ¡ la informaciÃ³n a la PC en este caso).", 0),
    STFNC__DESCRIPCION        (2001, subtotalFNC.class, DataType.Alfa,       8, "DescripciÃ³n del Subtotal, LÃ­nea de Texto Fiscal Variable - Este campo se mantiene por compatibilidad con modelos anteriores pero el mismo serÃ¡ ignorado, la descripciÃ³n serÃ¡ siempre â€œSubtotalâ€�.", true, 1),
    PDRTCFNC__DESCRIPCION    (2100, pagoCancelDescRecaFNC.class, DataType.Alfa,       26, "DescripciÃ³n: Texto Fiscal Variable. MÃ¡ximo de 26 caracteres en equipos de Tique-Factura / TNC, variable en equipos de Factura / NC.", 0),
    PDRTCFNC__MONTO          (2101, pagoCancelDescRecaFNC.class, DataType.Num2Dec,      11, "Monto del Pago / Descuento / Recargo (nnnnnnnnn.nn) Nota: Manejo de 9 enteros y 2 decimales, se debe enviar sin el punto.", 1),
    PDRTCFNC__CALIFICADOR    (2102, pagoCancelDescRecaFNC.class, DataType.Alfa,        1,"Calificador de Pago / Descuento / Recargo / Cancelar:'C'= 0x43, Cancelar Comprobante. 'T'= 0x54, Suma al Importe Pagado. 't'= 0x74, Anula un Pago hecho con â€˜Tâ€™. 'D'= 0x44, Realiza un Descuento Global de monto fijo. 'R'= 0x44, Realiza un Recargo Global de monto fijo.", 2),
    PFNC__DESCRIPCION        (2200, percepcionFNC.class, DataType.Alfa,       25, "DescripciÃ³n: Texto fiscal con descripciÃ³n del motivo de la percepciÃ³n. MÃ¡ximo de 25 Caracteres <aaa25aaa> completados con espacio a la derecha en impresiÃ³n de Tique-Factura. Longitud variable en impresoras de Factura con hoja suelta o formulario continuo. ", 0),
    PFNC__TIPO_PERCEPCION    (2201, percepcionFNC.class, DataType.Alfa,       1, "Tipo de PercepciÃ³n: Indica si es una PercepciÃ³n sobre IVA o es otro tipo de PercepciÃ³n <a>. â€˜Oâ€™= 0x4F (Decimal 79) Otro tipo de PercepciÃ³n (Perc. II.BB.). â€˜Iâ€™ = 0x49 (Decimal 73) PercepciÃ³n Global de IVA. â€˜Tâ€™= 0x54 (Decimal 84) PercepciÃ³n de IVA a una tasa determinada. Cualquier otra letra origina que se rechace el comando. Nota: En Comprobantes tipo â€˜Aâ€™ se aceptan percepciones tipo â€˜Oâ€™, â€˜Iâ€™ y â€˜Tâ€™ En Comprobantes tipo â€˜Bâ€™ se aceptan percepciones tipo â€˜Oâ€™ e â€˜Iâ€™. En Comprobantes tipo â€˜Câ€™ se aceptan percepciones tipo â€˜Oâ€™.", 1),
    PFNC__MONTO_PERCEPCION (2202, percepcionFNC.class, DataType.Num2Dec,      10, "Monto de la PercepciÃ³n <nnnnnnnn.nn>. (Manejo de 8 enteros y 2 decimales, se debe enviar sin el punto). SÃ³lo en el caso de que en el Campo 02 se coloque la opciÃ³n â€œTâ€� aquÃ­ se debe enviar la Tasa de IVA a la que se aplica la PercepciÃ³n (nn.nn) ", 2),
    PFNC__TASA_IVA            (2203, percepcionFNC.class, DataType.Num2Dec,       4, "Tasa de IVA a la que se aplica la PercepciÃ³n. (nn.nn). (Manejo de 2 enteros y 2 decimales, se debe enviar sin el punto). S Ã³lo en el caso de que en el Campo 02 se coloque la opciÃ³n â€œTâ€� aquÃ­ se debe enviar el Monto de la PercepciÃ³n <nnnnnnnn.nn>.", 3),
    CFNC__TIPO_DOCUMENTO   (2300, cerrarFNC.class, DataType.Alfa,       1, "Tipo de Documento Fiscal que se va a cerrar <a> que debe coincidir con el utilizado al abrir la Factura, Tique-Factura, NC Ã³ Tique-NC. â€˜Fâ€™= 0x46 Factura Fiscal â€˜Nâ€™= 0x4E Nota de CrÃ©dito Fiscal â€˜Tâ€™= 0x54 Tique-Factura Fiscal â€˜Mâ€™= 0x4D Tique-Nota de CrÃ©dito Fiscal Cualquier letra no aceptada por el modelo de controlador fiscal, origina que se rechace el comando.", 0),
    CFNC__LETRA_DOCUMENTO  (2301, cerrarFNC.class, DataType.Alfa,       1, "Letra del Documento Fiscal <a> que debe coincidir con el utilizado al A abrir una Factura Ã³ Tique-Factura. â€˜Aâ€™= 0x41 Ã³ â€˜Bâ€™= 0x42 Ã³ â€˜Câ€™= 0x43 Cualquier otra letra origina que se rechace el comando.", 1),
    CFNC__DESCRIP_EN_TOTAL  (2302, cerrarFNC.class, DataType.Alfa,       10, "DescripciÃ³n que se imprime en la lÃ­nea de TOTAL. Se debe considerar que los Ãºltimos 10 caracteres de la factura en hoja suelta o formulario continuo, estÃ¡n reservados para la impresiÃ³n de la palabra TOTAL. Esta descripciÃ³n no es utilizada en Tique-Factura, sÃ³lo se utiliza para impresiÃ³n de facturas en hoja suelta o formulario continuo. Para asegurar la compatibilidad se debe enviar en este campo el caracter ASCII DEL (0x7F o Dec 127) ", 2),
    EDF__NRO_LINEA            (2400, setDatoFijo.class, DataType.Integer, 5, "NÃºmero de LÃ­nea de Datos Fijos de encabezado o cola", 0),
    EDF__DATOS_FIJOS         (2401, setDatoFijo.class, DataType.Alfa, 40, "Datos Fijos: Hasta 40 bytes de Texto Fiscal", 1);


    Parametro(int codigo, Class comando, DataType type, int largo, String descripcion, Integer indice) {
        this.codigo = codigo;
        this.type = type;
        this.largo = largo;
        this.descripcion = descripcion;
        this.indice = indice;
        this.comando = comando;
    }

    Parametro(int codigo, Class comando, DataType type, int largo, String descripcion, boolean opcional, Integer indice) {
        this.codigo = codigo;
        this.type = type;
        this.largo = largo;
        this.descripcion = descripcion;
        this.opcional = opcional;
        this.indice = indice;
        this.comando = comando;
    }

    Class comando = null;
    Integer codigo = -1;
    String descripcion = "";
    DataType type = null;
    Integer largo = -1;
    boolean opcional = false;
    Integer indice = -1;

    public Integer getCodigo() {
        return codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public DataType getType() {
        return type;
    }

    public Integer getLargo() {
        return largo;
    }

    public Integer getIndice() {
        return indice;
    }

    public boolean isOpcional() {
        return opcional;
    }

    public Class getComando() {
        return comando;
    }

    public Parametro solveParam(Class comando, int index) {
        for(Parametro p : Parametro.values()) {
            if(p.getComando() == comando) {
                return p;
            }
        }

        return null;
    }

    public void setLargo(Integer largo) {
        this.largo = largo;
    }
    
}
